buildo/rc-datepicker

lib/DatePicker.jsx
lib/DatePickerInput.jsx
lib/datepicker.scss
lib/daypicker/DayPicker.jsx
lib/daypicker/DayPickerBody.jsx
lib/daypicker/DayPickerTop.jsx
lib/monthpicker/MonthPicker.jsx
lib/monthpicker/MonthPickerBody.jsx
lib/monthpicker/MonthPickerTop.jsx
lib/utils/DateUtils.js
lib/yearpicker/YearPicker.jsx
lib/yearpicker/YearPickerBody.jsx
lib/yearpicker/YearPickerTop.jsx
tests/DatePickerInput-test.js

datepicker should float above content if prop "floating" is true (true by default)

Floating datepicker

---

examples/example.css
package.json
src/DatePicker.js
src/DatePickerInput.js
src/datepicker.scss

#20: the calendar doesn't close when you click outside (closes #20)

---

examples/examples.js
examples/webpack.config.build.js
examples/webpack.config.js
src/DatePicker.js
src/monthpicker/MonthPicker.js
src/monthpicker/MonthPickerBody.js

#22: Should log a warning if required locale is not available (closes #22)

---

src/DatePicker.js
src/DatePickerInput.js

#25: Type in closeOnClickOutiside prop. (closes #25)

---

package.json
src/DatePickerInput.js

Could be useful have a prop to show or not the button icon for datepicker.

Optional input icon

---

src/DatePicker.js

#30: CI is failing due to lint error (closes #30)

---

src/DatePickerInput.js

#29: remove window.onclick listener in componentWillUnmount (closes #29)

---

src/DatePicker.js
src/DatePickerInput.js
src/Picker.js
src/Row.js
src/daypicker/DayPicker.js
src/daypicker/DayPickerBody.js
src/daypicker/DayPickerTop.js
src/monthpicker/MonthPicker.js
src/monthpicker/MonthPickerBody.js
src/monthpicker/MonthPickerTop.js
src/yearpicker/YearPicker.js
src/yearpicker/YearPickerBody.js
src/yearpicker/YearPickerTop.js

Not a meaningful one, but always happy to contribute :)

Using lodash range function, importing PropTypes to reduce verbosity.

---

src/PickerTop.js
src/daypicker/DayPickerTop.js
src/monthpicker/MonthPickerTop.js
src/yearpicker/YearPickerTop.js

Extracted PickerTop shared code.

DRYing PickerTop.

---

examples/examples.js
src/DatePicker.js
src/DatePickerInput.js

if you pass `value={undefined}` to `DatePicker` or `DatePickerInput` it should handle it and reset.

#55: handle undefined value (closes #55)

---

examples/examples.js
src/DatePicker.js
src/DatePickerInput.js
src/daypicker/DayPicker.js
src/daypicker/DayPickerTop.js
src/monthpicker/MonthPicker.js
src/monthpicker/MonthPickerBody.js
src/monthpicker/MonthPickerTop.js
src/utils/DateUtils.js
src/utils/ValueLinkMixin.js
src/yearpicker/YearPicker.js
src/yearpicker/YearPickerTop.js

Gcedo: Feature/dry datepickerinput

---

package.json

There was an error with the previous version preventing
me from starting the app.

upgrade babel-eslint

---

examples/webpack.config.build.js
examples/webpack.config.js
package.json
src/DatePickerInput.js
src/daypicker/DayPickerBody.js
src/daypicker/DayPickerTop.js
src/monthpicker/MonthPickerBody.js
src/monthpicker/MonthPickerTop.js
src/utils/DateUtils.js
src/yearpicker/YearPickerBody.js
src/yearpicker/YearPickerTop.js

#73: Update lodash to ^4 (closes #73)

---

src/DatePicker.js
src/DatePickerInput.js

Check window event target instead of stopPropogation

---

src/DatePicker.js

#75: 3.1.0 break change mode button (closes #75)

---

src/DatePickerInput.js

Issue #83
first click doesn't call `onChange`
Chrome and IE11

#83: [IE] datepicker returns InvalidDate at first click (closes #83)

---

examples/examples.js
examples/index.html
src/DatePickerInput.js
src/style.scss

Issue #82
[![https://gyazo.com/4c38156510cbd12655eac5abd90d9b41](https://i.gyazo.com/4c38156510cbd12655eac5abd90d9b41.gif)](https://gyazo.com/4c38156510cbd12655eac5abd90d9b41)

#82: [style] improve button style (closes #82)

---

.eslintrc
src/DatePickerInput.js
src/Picker.js
src/style.scss

#86: [style] improve picker style (closes #86)

---

src/DatePickerInput.js

Issue #88
tested with demo:
- write in input --> value is updated
- write then delete --> you can delete also the first character (this is the bug fixed with second commit)

#88: Find an alternative to valueLink (closes #88)

---

examples/examples.js
src/style.scss

Issue #98
- reviewed offline with alessandra
Here's a screenshot but as there are many possible states please test it offline :)

#98: [style] update style with new mockup (closes #98)

---

src/DatePickerInput.js

Hey there,
this PR was opened using [linto](https://github.com/buildo/linto).
Usually this means the shared ESLint config has been updated and these are the changes needed to comply with the new config.
The diff for this PR has been generated running `eslint --fix` using the updated ESLint config. Depending on the specific change, you may need to apply some manual fixes too.
Hope this helped!
Your friend,
linto 💄

💄  linto fix

---

examples/examples.js
src/DatePickerInput.js
src/style.scss

#109: add "disabled" functionality to DatePickerInput (closes #109)

---

src/DatePicker.js
src/DatePickerInput.js
src/style.scss

#112: DatePickerInput: add ability to open the popup on top (closes #112)

---

package.json

#120: add "files" in package.json (closes #120)

---

.npmignore
index.d.ts
package.json
yarn.lock

Closes #105
- `DatePickerInput` type are correctly detected by vscode ✅ 
- `DatePicker` type are correctly detected by vscode ✅ 

#105: typescript support (closes #105)

---

.drone.yml
examples/examples.js
package.json
test/tests/DatePickerInput-test.js

Closes #124
- CI should be happy
> A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.
> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}

#124: backport scriptoni@0.6 (closes #124)

---

src/DatePickerInput.js

Closes #126
> A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.
> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}

#126: Ci is failing with Error: Missing description for prop 'startDate' in 'DatePickerInput'. (closes #126)

---

package.json

Closes #146
> A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.
> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}

#146: @types/react should not be a dependency (closes #146)

---

index.d.ts

Added "placeholder" prop definition configurable via props

Added "placeholder" props definition

---

src/DatePickerInput.js

The placeholder props was not working.

Fix #162 Placeholder not showing
